-- MySQL Script generated by MySQL Workbench
-- Fri Jul  8 00:45:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema delivery
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema delivery
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `delivery` DEFAULT CHARACTER SET utf8 ;
USE `delivery` ;

-- -----------------------------------------------------
-- Table `delivery`.`tb_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `lastName` VARCHAR(60) NOT NULL,
  `birthday` DATETIME NOT NULL,
  `docment` VARCHAR(14) NOT NULL,
  `email` VARCHAR(140) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `deviceToken` VARCHAR(255) NULL,
  `city` VARCHAR(45) NOT NULL,
  `status` VARCHAR(1) NOT NULL,
  `dateCreated` DATETIME DEFAULT NOW(),
  `dateUpdated` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `docment_UNIQUE` (`docment` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`tb_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_permissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `status` VARCHAR(1) NOT NULL,
  `dateCreated` DATETIME DEFAULT NOW(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`tb_user_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_user_permissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `idPermission` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_user_permissions_tb_users_idx` (`idUser` ASC) ,
  INDEX `fk_tb_user_permissions_tb_permissions1_idx` (`idPermission` ASC) ,
  CONSTRAINT `fk_tb_user_permissions_tb_users`
    FOREIGN KEY (`idUser`)
    REFERENCES `delivery`.`tb_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_user_permissions_tb_permissions1`
    FOREIGN KEY (`idPermission`)
    REFERENCES `delivery`.`tb_permissions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`tb_estabelecimentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_estabelecimentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `phone` VARCHAR(11) NULL,
  `description` VARCHAR(150) NULL,
  `imgUrl` VARCHAR(255) NULL,
  `latitude` VARCHAR(15) NOT NULL,
  `longitude` VARCHAR(15) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `numberAddress` VARCHAR(6) NOT NULL,
  `optionalAddress` VARCHAR(15) NULL,
  `status` VARCHAR(1) NULL,
  `dateCreated` DATETIME DEFAULT NOW(),
  `dateUpdated` DATETIME NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) ,
  INDEX `fk_tb_estabelecimentos_tb_users1_idx` (`userId` ASC) ,
  CONSTRAINT `fk_tb_estabelecimentos_tb_users1`
    FOREIGN KEY (`userId`)
    REFERENCES `delivery`.`tb_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`tb_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(150) NULL,
  `dateCreated` DATETIME DEFAULT NOW(),
  `dateUpdated` DATETIME NULL,
  `status` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`tb_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `status` VARCHAR(1) NOT NULL,
  `dateCreated` DATETIME DEFAULT NOW(),
  `dateUpdated` DATETIME NULL,
  `idCategories` INT NOT NULL,
  `idEstabelecimento` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_products_tb_categories1_idx` (`idCategories` ASC) ,
  INDEX `fk_tb_products_tb_estabelecimentos1_idx` (`idEstabelecimento` ASC) ,
  CONSTRAINT `fk_tb_products_tb_categories1`
    FOREIGN KEY (`idCategories`)
    REFERENCES `delivery`.`tb_categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_products_tb_estabelecimentos1`
    FOREIGN KEY (`idEstabelecimento`)
    REFERENCES `delivery`.`tb_estabelecimentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`tb_vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_vendas` (
  `id` INT NOT NULL,
  `status` VARCHAR(1) NOT NULL,
  `dateCreated` DATETIME DEFAULT NOW(),
  `dateUpdated` DATETIME NULL,
  `userId` INT NOT NULL,
  `productId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_vendas_tb_users1_idx` (`userId` ASC) ,
  INDEX `fk_tb_vendas_tb_products1_idx` (`productId` ASC) ,
  CONSTRAINT `fk_tb_vendas_tb_users1`
    FOREIGN KEY (`userId`)
    REFERENCES `delivery`.`tb_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_vendas_tb_products1`
    FOREIGN KEY (`productId`)
    REFERENCES `delivery`.`tb_products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`tb_push`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_push` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(120) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `dateCreated` DATETIME DEFAULT NOW(),
  `tb_users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_push_tb_users1_idx` (`tb_users_id` ASC) ,
  CONSTRAINT `fk_tb_push_tb_users1`
    FOREIGN KEY (`tb_users_id`)
    REFERENCES `delivery`.`tb_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
